# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Kasa Główna'), (2, 'Kasa Fiskalna'), (3, 'Konto Bankowe IDEA'), (4, 'Konto Bankowe INTELIGO'), (5, 'Konto Bankowe NEST')], max_length=32)),
                ('number', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=128)),
                ('nip', models.IntegerField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=28, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, unique=True)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_sale', models.DateField()),
                ('date_to_pay', models.DateField()),
                ('if_payment', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wesol.Contractors')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Gotówka'), (2, 'Przelew'), (3, 'Karta płatnicza')])),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wesol.Accounts')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wesol.Contractors')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wesol.Invoices')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('tax', models.IntegerField(choices=[(1, 'A - 23%'), (2, 'B - 8%'), (3, 'C - ?!'), (4, 'D - ?!'), (5, 'G - ?!')])),
                ('used_in', models.IntegerField(blank=True, choices=[(1, 'Do sprzedaży'), (2, 'Na imprezy'), (3, 'Użytek własny'), (4, 'ogólne')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInvoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wesol.Invoices')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wesol.Products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='invoice',
            field=models.ManyToManyField(related_name='products', through='wesol.ProductsInvoices', to='wesol.Invoices'),
        ),
    ]
