# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesol', '0002_auto_20170829_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinvoices',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
