# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wesol', '0003_auto_20170829_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_card_take', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wesol.Payments')),
            ],
        ),
    ]
