# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesol', '0005_auto_20170829_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='counted_money_in_drawer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
