# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wesol', '0008_auto_20170830_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='invoice',
        ),
    ]
