# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesol', '0009_remove_products_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='actual_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
