# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesol', '0012_productsinvoices_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='actual_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
